// <auto-generated />
using System;
using CMS.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CMS.Models.CapChungChi", b =>
                {
                    b.Property<int>("IdKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("IdNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("AnhChungChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLoaiDaoTao")
                        .HasColumnType("int");

                    b.Property<bool>("KetQua")
                        .HasColumnType("bit");

                    b.HasKey("IdKhoaHoc", "IdNhanVien");

                    b.HasIndex("IdLoaiDaoTao");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("tblCapChungChi");
                });

            modelBuilder.Entity("CMS.Models.ChucDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenChucDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblChucDanh");
                });

            modelBuilder.Entity("CMS.Models.ChungChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdNhomChungChi")
                        .HasColumnType("int");

                    b.Property<string>("TenChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdNhomChungChi");

                    b.ToTable("tblChungChi");
                });

            modelBuilder.Entity("CMS.Models.DonViDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenDonViDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblDonViDaoTao");
                });

            modelBuilder.Entity("CMS.Models.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdDonViDaoTao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDonViDaoTao");

                    b.ToTable("tblGiaoVien");
                });

            modelBuilder.Entity("CMS.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDonViDaoTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDonViDaoTao");

                    b.ToTable("tblHopDong");
                });

            modelBuilder.Entity("CMS.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChungChi")
                        .HasColumnType("int");

                    b.Property<int>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<int>("IdQuyetDinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdChungChi");

                    b.HasIndex("IdGiaoVien");

                    b.HasIndex("IdQuyetDinh");

                    b.ToTable("tblKhoaHoc");
                });

            modelBuilder.Entity("CMS.Models.LoaiDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenLoaiDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblLoaiDaoTao");
                });

            modelBuilder.Entity("CMS.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdChucDanh")
                        .HasColumnType("int");

                    b.Property<int>("IdPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdChucDanh");

                    b.HasIndex("IdPhongBan");

                    b.ToTable("tblNhanVien");
                });

            modelBuilder.Entity("CMS.Models.NhomChungChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblNhomChungChi");
                });

            modelBuilder.Entity("CMS.Models.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblPhongBan");
                });

            modelBuilder.Entity("CMS.Models.QuyetDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDonViDaoTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDonViDaoTao");

                    b.ToTable("tblQuyetDinh");
                });

            modelBuilder.Entity("CMS.Models.CapChungChi", b =>
                {
                    b.HasOne("CMS.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("CapChungChis")
                        .HasForeignKey("IdKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMS.Models.LoaiDaoTao", "LoaiDaoTao")
                        .WithMany("CapChungChis")
                        .HasForeignKey("IdLoaiDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMS.Models.NhanVien", "NhanVien")
                        .WithMany("CapChungChis")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("LoaiDaoTao");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("CMS.Models.ChungChi", b =>
                {
                    b.HasOne("CMS.Models.NhomChungChi", "NhomChungChi")
                        .WithMany("ChungChis")
                        .HasForeignKey("IdNhomChungChi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomChungChi");
                });

            modelBuilder.Entity("CMS.Models.GiaoVien", b =>
                {
                    b.HasOne("CMS.Models.DonViDaoTao", "DonViDaoTao")
                        .WithMany("GiaoViens")
                        .HasForeignKey("IdDonViDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViDaoTao");
                });

            modelBuilder.Entity("CMS.Models.HopDong", b =>
                {
                    b.HasOne("CMS.Models.DonViDaoTao", "DonViDaoTao")
                        .WithMany("HopDongs")
                        .HasForeignKey("IdDonViDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViDaoTao");
                });

            modelBuilder.Entity("CMS.Models.KhoaHoc", b =>
                {
                    b.HasOne("CMS.Models.ChungChi", "ChungChi")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("IdChungChi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMS.Models.GiaoVien", "GiaoVien")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("IdGiaoVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CMS.Models.QuyetDinh", "QuyetDinh")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("IdQuyetDinh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChungChi");

                    b.Navigation("GiaoVien");

                    b.Navigation("QuyetDinh");
                });

            modelBuilder.Entity("CMS.Models.NhanVien", b =>
                {
                    b.HasOne("CMS.Models.ChucDanh", "ChucDanh")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdChucDanh")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMS.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdPhongBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChucDanh");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("CMS.Models.QuyetDinh", b =>
                {
                    b.HasOne("CMS.Models.DonViDaoTao", "DonViDaoTao")
                        .WithMany("QuyetDinhs")
                        .HasForeignKey("IdDonViDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonViDaoTao");
                });

            modelBuilder.Entity("CMS.Models.ChucDanh", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("CMS.Models.ChungChi", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("CMS.Models.DonViDaoTao", b =>
                {
                    b.Navigation("GiaoViens");

                    b.Navigation("HopDongs");

                    b.Navigation("QuyetDinhs");
                });

            modelBuilder.Entity("CMS.Models.GiaoVien", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("CMS.Models.KhoaHoc", b =>
                {
                    b.Navigation("CapChungChis");
                });

            modelBuilder.Entity("CMS.Models.LoaiDaoTao", b =>
                {
                    b.Navigation("CapChungChis");
                });

            modelBuilder.Entity("CMS.Models.NhanVien", b =>
                {
                    b.Navigation("CapChungChis");
                });

            modelBuilder.Entity("CMS.Models.NhomChungChi", b =>
                {
                    b.Navigation("ChungChis");
                });

            modelBuilder.Entity("CMS.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("CMS.Models.QuyetDinh", b =>
                {
                    b.Navigation("KhoaHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
