//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Configuration;
    using System.Security.Cryptography;
    using System.Text;

    public partial class EMMEntities : DbContext
    {
        public EMMEntities()
        : base(GetConnectionStringUseEntity())
        { }

        //public EMMEntities()
        //    : base("name=EMMEntities")
        //{
        //}

        public static string GetConnectionStringUseEntity()
        {
            System.Diagnostics.Debug.WriteLine($"con: {Encrypt("Data Source = QUOC-IT; database = EMM; uid = sa; pwd = 123@123a")}");
            string connectionString = ConfigurationManager.ConnectionStrings["EMMEntities"].ConnectionString;
            //return connectionString;
            return Decrypt(connectionString);
        }
        private static string Key = "tbBquB+78++VOyYeZWsmZg==";
        public static string Encrypt(string toEncrypt)
        {
            bool useHashing = true;
            byte[] keyArray;
            byte[] toEncryptArray = UTF8Encoding.UTF8.GetBytes(toEncrypt);

            if (useHashing)
            {
                MD5CryptoServiceProvider hashmd5 = new MD5CryptoServiceProvider();
                keyArray = hashmd5.ComputeHash(UTF8Encoding.UTF8.GetBytes(Key));
            }
            else
                keyArray = UTF8Encoding.UTF8.GetBytes(Key);

            TripleDESCryptoServiceProvider tdes = new TripleDESCryptoServiceProvider();
            tdes.Key = keyArray;
            tdes.Mode = CipherMode.ECB;
            tdes.Padding = PaddingMode.PKCS7;

            ICryptoTransform cTransform = tdes.CreateEncryptor();
            byte[] resultArray = cTransform.TransformFinalBlock(toEncryptArray, 0, toEncryptArray.Length);

            return Convert.ToBase64String(resultArray, 0, resultArray.Length);
        }

        public static string Decrypt(string toDecrypt)
        {
            bool useHashing = true;
            byte[] keyArray;
            byte[] toEncryptArray = Convert.FromBase64String(toDecrypt);

            if (useHashing)
            {
                MD5CryptoServiceProvider hashmd5 = new MD5CryptoServiceProvider();
                keyArray = hashmd5.ComputeHash(UTF8Encoding.UTF8.GetBytes(Key));
            }
            else
                keyArray = UTF8Encoding.UTF8.GetBytes(Key);

            TripleDESCryptoServiceProvider tdes = new TripleDESCryptoServiceProvider();
            tdes.Key = keyArray;
            tdes.Mode = CipherMode.ECB;
            tdes.Padding = PaddingMode.PKCS7;

            ICryptoTransform cTransform = tdes.CreateDecryptor();
            byte[] resultArray = cTransform.TransformFinalBlock(toEncryptArray, 0, toEncryptArray.Length);

            return UTF8Encoding.UTF8.GetString(resultArray);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblCapBaoDuong> tblCapBaoDuongs { get; set; }
        public virtual DbSet<tblCapBaoDuongVatTu> tblCapBaoDuongVatTus { get; set; }
        public virtual DbSet<tblCongTy> tblCongTies { get; set; }
        public virtual DbSet<tblDinhMucNhienLieu> tblDinhMucNhienLieux { get; set; }
        public virtual DbSet<tblDinhMucTheoNgay> tblDinhMucTheoNgays { get; set; }
        public virtual DbSet<tblFunction> tblFunctions { get; set; }
        public virtual DbSet<tblKieuBaoDuong> tblKieuBaoDuongs { get; set; }
        public virtual DbSet<tblLoaiBaoDuong> tblLoaiBaoDuongs { get; set; }
        public virtual DbSet<tblLoaiHuHong> tblLoaiHuHongs { get; set; }
        public virtual DbSet<tblLoaiTrangThietBi> tblLoaiTrangThietBis { get; set; }
        public virtual DbSet<tblLoaiVatTu> tblLoaiVatTus { get; set; }
        public virtual DbSet<tblNapNhienLieu> tblNapNhienLieux { get; set; }
        public virtual DbSet<tblNhaCungCap> tblNhaCungCaps { get; set; }
        public virtual DbSet<tblNhatKyHoatDong> tblNhatKyHoatDongs { get; set; }
        public virtual DbSet<tblPhongBan> tblPhongBans { get; set; }
        public virtual DbSet<tblQuyTrinhBaoDuong> tblQuyTrinhBaoDuongs { get; set; }
        public virtual DbSet<tblRight> tblRights { get; set; }
        public virtual DbSet<tblRightsInRole> tblRightsInRoles { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSystemSetting> tblSystemSettings { get; set; }
        public virtual DbSet<tblTanSuatHoatDong> tblTanSuatHoatDongs { get; set; }
        public virtual DbSet<tblTheBaoDuong> tblTheBaoDuongs { get; set; }
        public virtual DbSet<tblTrangThietBi> tblTrangThietBis { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblVatTu> tblVatTus { get; set; }
        public virtual DbSet<tblCongViec> tblCongViecs { get; set; }
        public virtual DbSet<tblChiTietBaoDuong> tblChiTietBaoDuongs { get; set; }
        public virtual DbSet<tblChiTietBaoDuongCongViec> tblChiTietBaoDuongCongViecs { get; set; }
        public virtual DbSet<tblHangMucBaoDuong> tblHangMucBaoDuongs { get; set; }
        public virtual DbSet<tblNhomHangMucBaoDuong> tblNhomHangMucBaoDuongs { get; set; }
        public virtual DbSet<tblNhomTrangThietBi> tblNhomTrangThietBis { get; set; }
        public virtual DbSet<tblHangMucLoaiTrangThietBi> tblHangMucLoaiTrangThietBis { get; set; }
        public virtual DbSet<tblCapBaoDuongCongViec> tblCapBaoDuongCongViecs { get; set; }
        public virtual DbSet<tblTanSuatHoatDongThucTe> tblTanSuatHoatDongThucTe { get; set; }
        public virtual DbSet<tblSkySoft> tblSkySoft { get; set; }
        public virtual DbSet<tblPhieuSuaChua> tblPhieuSuaChuas { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_BaoCaoDinhMucNhienLieu(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoDinhMucNhienLieu", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, tuNgayParameter, denNgayParameter);
        }
    
        public virtual int sp_CanhBaoBaoDuongTheoGioTungXe(Nullable<int> iD, ObjectParameter ngayBaoDuongTiepTheo, ObjectParameter soNgayConLaiChoLanBaoDuongTiepTheo, ObjectParameter soGioMocBaoDuongTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CanhBaoBaoDuongTheoGioTungXe", iDParameter, ngayBaoDuongTiepTheo, soNgayConLaiChoLanBaoDuongTiepTheo, soGioMocBaoDuongTiepTheo);
        }
    
        public virtual int sp_CanhBaoBaoDuongTheoKmTungXe(Nullable<int> iD, ObjectParameter ngayBaoDuongTiepTheo, ObjectParameter soNgayConLaiChoLanBaoDuongTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CanhBaoBaoDuongTheoKmTungXe", iDParameter, ngayBaoDuongTiepTheo, soNgayConLaiChoLanBaoDuongTiepTheo);
        }
    
        public virtual int sp_CanhBaoBaoDuongTheoThangCacXe(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, Nullable<int> soNgayPhamViCanhBao)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var soNgayPhamViCanhBaoParameter = soNgayPhamViCanhBao.HasValue ?
                new ObjectParameter("SoNgayPhamViCanhBao", soNgayPhamViCanhBao) :
                new ObjectParameter("SoNgayPhamViCanhBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CanhBaoBaoDuongTheoThangCacXe", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, soNgayPhamViCanhBaoParameter);
        }
    
        public virtual int sp_CanhBaoBaoDuongTheoThangTungXe(Nullable<int> iD, ObjectParameter ngayBaoDuongTiepTheo, ObjectParameter soNgayConLaiChoLanBaoDuongTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CanhBaoBaoDuongTheoThangTungXe", iDParameter, ngayBaoDuongTiepTheo, soNgayConLaiChoLanBaoDuongTiepTheo);
        }
    
        public virtual int sp_CanhBaoNgayDangKiemKeTiep(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string tenXe, Nullable<int> soNgayPhamViCanhBao)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var tenXeParameter = tenXe != null ?
                new ObjectParameter("TenXe", tenXe) :
                new ObjectParameter("TenXe", typeof(string));
    
            var soNgayPhamViCanhBaoParameter = soNgayPhamViCanhBao.HasValue ?
                new ObjectParameter("SoNgayPhamViCanhBao", soNgayPhamViCanhBao) :
                new ObjectParameter("SoNgayPhamViCanhBao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CanhBaoNgayDangKiemKeTiep", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, tenXeParameter, soNgayPhamViCanhBaoParameter);
        }
    
        public virtual int sp_CanhBaoNgayDangKiemKeTiepTungXe(Nullable<int> iD, ObjectParameter ngayDangKiemTiepTheo, ObjectParameter soNgayConLaiChoLanDangKiepTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CanhBaoNgayDangKiemKeTiepTungXe", iDParameter, ngayDangKiemTiepTheo, soNgayConLaiChoLanDangKiepTiepTheo);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_Search_DinhMucNhienLieu(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_DinhMucNhienLieu", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_Search_LoaiTrangThietBi(Nullable<int> iDNhomTrangThietBi, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_LoaiTrangThietBi", iDNhomTrangThietBiParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_Search_NapNhienLieu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_NapNhienLieu", tuNgayParameter, denNgayParameter, iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_Search_NhatKyHoatDong(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_NhatKyHoatDong", tuNgayParameter, denNgayParameter, iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_Search_TrangThietBi(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_TrangThietBi", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchCompany(string tenVietTat, string tenDayDu, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var tenVietTatParameter = tenVietTat != null ?
                new ObjectParameter("TenVietTat", tenVietTat) :
                new ObjectParameter("TenVietTat", typeof(string));
    
            var tenDayDuParameter = tenDayDu != null ?
                new ObjectParameter("TenDayDu", tenDayDu) :
                new ObjectParameter("TenDayDu", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchCompany", tenVietTatParameter, tenDayDuParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchFailure(string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchFailure", tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchLoaiBaoDuong(Nullable<int> iDKieuBaoDuong, string tenLoaiBaoDuong, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDKieuBaoDuongParameter = iDKieuBaoDuong.HasValue ?
                new ObjectParameter("IDKieuBaoDuong", iDKieuBaoDuong) :
                new ObjectParameter("IDKieuBaoDuong", typeof(int));
    
            var tenLoaiBaoDuongParameter = tenLoaiBaoDuong != null ?
                new ObjectParameter("TenLoaiBaoDuong", tenLoaiBaoDuong) :
                new ObjectParameter("TenLoaiBaoDuong", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchLoaiBaoDuong", iDKieuBaoDuongParameter, tenLoaiBaoDuongParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchMaintenance(Nullable<int> iDNhomHangMucBaoDuong, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDNhomHangMucBaoDuongParameter = iDNhomHangMucBaoDuong.HasValue ?
                new ObjectParameter("IDNhomHangMucBaoDuong", iDNhomHangMucBaoDuong) :
                new ObjectParameter("IDNhomHangMucBaoDuong", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchMaintenance", iDNhomHangMucBaoDuongParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchMaintenanceGroup(string ten, ObjectParameter totalRecord)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchMaintenanceGroup", tenParameter, totalRecord);
        }
    
        public virtual int sp_SearchMaintenanceLevel(Nullable<int> iDKieuBaoDuong, Nullable<int> iDLoaiBaoDuong, string ten, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDKieuBaoDuongParameter = iDKieuBaoDuong.HasValue ?
                new ObjectParameter("IDKieuBaoDuong", iDKieuBaoDuong) :
                new ObjectParameter("IDKieuBaoDuong", typeof(int));
    
            var iDLoaiBaoDuongParameter = iDLoaiBaoDuong.HasValue ?
                new ObjectParameter("IDLoaiBaoDuong", iDLoaiBaoDuong) :
                new ObjectParameter("IDLoaiBaoDuong", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchMaintenanceLevel", iDKieuBaoDuongParameter, iDLoaiBaoDuongParameter, tenParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchRole(string roleName, string description, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchRole", roleNameParameter, descriptionParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchUser(string username, string fullname, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("Fullname", fullname) :
                new ObjectParameter("Fullname", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchUser", usernameParameter, fullnameParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_TinhDinhMucTheoNgay(Nullable<System.DateTime> ngay, Nullable<int> iDTrangThietBi)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(System.DateTime));
    
            var iDTrangThietBiParameter = iDTrangThietBi.HasValue ?
                new ObjectParameter("IDTrangThietBi", iDTrangThietBi) :
                new ObjectParameter("IDTrangThietBi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhDinhMucTheoNgay", ngayParameter, iDTrangThietBiParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int spFunction_GetAllByIdUser(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFunction_GetAllByIdUser", idUserParameter);
        }
    
        public virtual ObjectResult<spUser_GetRightsInRolesByIdUser_Result> spUser_GetRightsInRolesByIdUser(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUser_GetRightsInRolesByIdUser_Result>("spUser_GetRightsInRolesByIdUser", idUserParameter);
        }
    
        public virtual ObjectResult<tblFunction> Function_GetAllByIdUser(Nullable<int> idUser)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblFunction>("Function_GetAllByIdUser", idUserParameter);
        }
    
        public virtual ObjectResult<tblFunction> Function_GetAllByIdUser(Nullable<int> idUser, MergeOption mergeOption)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("IdUser", idUser) :
                new ObjectParameter("IdUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tblFunction>("Function_GetAllByIdUser", mergeOption, idUserParameter);
        }
    
        public virtual int sp_Search_TheBaoDuong(Nullable<System.DateTime> ngayNhapTuNgay, Nullable<System.DateTime> ngayNhapDenNgay, Nullable<System.DateTime> ngayBaoDuongTuNgay, Nullable<System.DateTime> ngayBaoDuongDenNgay, Nullable<int> iDCongTy, Nullable<int> iDKieuBaoDuong, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string maThe, string bienSo, string trangThai, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var ngayNhapTuNgayParameter = ngayNhapTuNgay.HasValue ?
                new ObjectParameter("NgayNhapTuNgay", ngayNhapTuNgay) :
                new ObjectParameter("NgayNhapTuNgay", typeof(System.DateTime));
    
            var ngayNhapDenNgayParameter = ngayNhapDenNgay.HasValue ?
                new ObjectParameter("NgayNhapDenNgay", ngayNhapDenNgay) :
                new ObjectParameter("NgayNhapDenNgay", typeof(System.DateTime));
    
            var ngayBaoDuongTuNgayParameter = ngayBaoDuongTuNgay.HasValue ?
                new ObjectParameter("NgayBaoDuongTuNgay", ngayBaoDuongTuNgay) :
                new ObjectParameter("NgayBaoDuongTuNgay", typeof(System.DateTime));
    
            var ngayBaoDuongDenNgayParameter = ngayBaoDuongDenNgay.HasValue ?
                new ObjectParameter("NgayBaoDuongDenNgay", ngayBaoDuongDenNgay) :
                new ObjectParameter("NgayBaoDuongDenNgay", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDKieuBaoDuongParameter = iDKieuBaoDuong.HasValue ?
                new ObjectParameter("IDKieuBaoDuong", iDKieuBaoDuong) :
                new ObjectParameter("IDKieuBaoDuong", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var maTheParameter = maThe != null ?
                new ObjectParameter("MaThe", maThe) :
                new ObjectParameter("MaThe", typeof(string));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_TheBaoDuong", ngayNhapTuNgayParameter, ngayNhapDenNgayParameter, ngayBaoDuongTuNgayParameter, ngayBaoDuongDenNgayParameter, iDCongTyParameter, iDKieuBaoDuongParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, maTheParameter, bienSoParameter, trangThaiParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_SearchFrequency(Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SearchFrequency", iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_LayDanhSachHangMucBaoDuong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayDanhSachHangMucBaoDuong");
        }
    
        public virtual int sp_GetMaintenanceDetail(Nullable<int> idMaintenance)
        {
            var idMaintenanceParameter = idMaintenance.HasValue ?
                new ObjectParameter("idMaintenance", idMaintenance) :
                new ObjectParameter("idMaintenance", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetMaintenanceDetail", idMaintenanceParameter);
        }
    
        public virtual int sp_Search_HangMucCapBaoDuong(Nullable<int> iDKieuBaoDuong, Nullable<int> iDLoaiBaoDuong, Nullable<int> iDCapBaoDuong, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDKieuBaoDuongParameter = iDKieuBaoDuong.HasValue ?
                new ObjectParameter("IDKieuBaoDuong", iDKieuBaoDuong) :
                new ObjectParameter("IDKieuBaoDuong", typeof(int));
    
            var iDLoaiBaoDuongParameter = iDLoaiBaoDuong.HasValue ?
                new ObjectParameter("IDLoaiBaoDuong", iDLoaiBaoDuong) :
                new ObjectParameter("IDLoaiBaoDuong", typeof(int));
    
            var iDCapBaoDuongParameter = iDCapBaoDuong.HasValue ?
                new ObjectParameter("IDCapBaoDuong", iDCapBaoDuong) :
                new ObjectParameter("IDCapBaoDuong", typeof(int));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_HangMucCapBaoDuong", iDKieuBaoDuongParameter, iDLoaiBaoDuongParameter, iDCapBaoDuongParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_GetAllMaintenance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetAllMaintenance");
        }
    
        public virtual int sp_LayHangMucBaoDuongDeTaoMauForm(string maintenanceList)
        {
            var maintenanceListParameter = maintenanceList != null ?
                new ObjectParameter("maintenanceList", maintenanceList) :
                new ObjectParameter("maintenanceList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayHangMucBaoDuongDeTaoMauForm", maintenanceListParameter);
        }
    
        public virtual int sp_LayHangMucBaoDuongTheoNhomTrangThietBi(Nullable<int> iDNhomTrangThietBi)
        {
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayHangMucBaoDuongTheoNhomTrangThietBi", iDNhomTrangThietBiParameter);
        }
    
        public virtual int sp_Search_MauInTheBaoDuong(Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_MauInTheBaoDuong", iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        [DbFunction("EMMEntities", "Split")]
        public virtual IQueryable<string> Split(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[EMMEntities].[Split](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual int sp_LayHangMucBaoDuongTheoLoaiTrangThietBi(Nullable<int> iDLoaiTrangThietBi)
        {
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayHangMucBaoDuongTheoLoaiTrangThietBi", iDLoaiTrangThietBiParameter);
        }
    
        public virtual int sp_LayNoiDungBaoDuongTheoLoaiXe(Nullable<int> iDLoaiTrangThietBi)
        {
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayNoiDungBaoDuongTheoLoaiXe", iDLoaiTrangThietBiParameter);
        }
    
        public virtual int sp_DeleteMaintenanceParentGroup(Nullable<int> idMaintenanceGroup)
        {
            var idMaintenanceGroupParameter = idMaintenanceGroup.HasValue ?
                new ObjectParameter("IdMaintenanceGroup", idMaintenanceGroup) :
                new ObjectParameter("IdMaintenanceGroup", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteMaintenanceParentGroup", idMaintenanceGroupParameter);
        }
    
        public virtual int sp_GetMaintenanceParentGroup(Nullable<int> idMaintenanceGroup)
        {
            var idMaintenanceGroupParameter = idMaintenanceGroup.HasValue ?
                new ObjectParameter("IdMaintenanceGroup", idMaintenanceGroup) :
                new ObjectParameter("IdMaintenanceGroup", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetMaintenanceParentGroup", idMaintenanceGroupParameter);
        }
    
        public virtual int sp_GetTaskListForPrint(ObjectParameter taskNameList)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetTaskListForPrint", taskNameList);
        }
    
        public virtual int sp_Search_NhomTrangThietBi(string tenNhom, Nullable<int> pageNo, Nullable<int> pageSize, string sortColumn, string sortOrder, ObjectParameter totalRecord)
        {
            var tenNhomParameter = tenNhom != null ?
                new ObjectParameter("TenNhom", tenNhom) :
                new ObjectParameter("TenNhom", typeof(string));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortOrderParameter = sortOrder != null ?
                new ObjectParameter("SortOrder", sortOrder) :
                new ObjectParameter("SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_NhomTrangThietBi", tenNhomParameter, pageNoParameter, pageSizeParameter, sortColumnParameter, sortOrderParameter, totalRecord);
        }
    
        public virtual int sp_DeleteNhaCungCap(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteNhaCungCap", iDParameter);
        }
    
        public virtual ObjectResult<sp_GetAllNhaCungCap_Result> sp_GetAllNhaCungCap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllNhaCungCap_Result>("sp_GetAllNhaCungCap");
        }
    
        public virtual int sp_GetMaintenanceParentGroupForAddMaintenance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetMaintenanceParentGroupForAddMaintenance");
        }
    
        public virtual ObjectResult<sp_GetNhaCungCapById_Result> sp_GetNhaCungCapById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetNhaCungCapById_Result>("sp_GetNhaCungCapById", idParameter);
        }
    
        public virtual int sp_InsertNhaCungCap(string ten, string diaChi, string soDienThoai, string email)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNhaCungCap", tenParameter, diaChiParameter, soDienThoaiParameter, emailParameter);
        }
    
        public virtual int sp_Search_GetAllMaintenance(Nullable<int> idMaintenanceGroup)
        {
            var idMaintenanceGroupParameter = idMaintenanceGroup.HasValue ?
                new ObjectParameter("IdMaintenanceGroup", idMaintenanceGroup) :
                new ObjectParameter("IdMaintenanceGroup", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Search_GetAllMaintenance", idMaintenanceGroupParameter);
        }
    
        public virtual ObjectResult<sp_Search_TrangThietBi_Export_Result> sp_Search_TrangThietBi_Export(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string ten)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Search_TrangThietBi_Export_Result>("sp_Search_TrangThietBi_Export", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, tenParameter);
        }
    
        public virtual int sp_UpdateNhaCungCap(Nullable<int> iD, string ten, string diaChi, string soDienThoai, string email)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNhaCungCap", iDParameter, tenParameter, diaChiParameter, soDienThoaiParameter, emailParameter);
        }
    
        public virtual int spAddEmployee(string name, string city, string department, string gender)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddEmployee", nameParameter, cityParameter, departmentParameter, genderParameter);
        }
    
        public virtual int spDeleteEmployee(Nullable<int> empId)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteEmployee", empIdParameter);
        }
    
        public virtual ObjectResult<spGetAllEmployees_Result> spGetAllEmployees()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllEmployees_Result>("spGetAllEmployees");
        }
    
        public virtual int spUpdateEmployee(Nullable<int> empId, string name, string city, string department, string gender)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateEmployee", empIdParameter, nameParameter, cityParameter, departmentParameter, genderParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoDanhSachBaoDuong_Result> sp_BaoCaoDanhSachBaoDuong(Nullable<System.DateTime> ngayNhapTuNgay, Nullable<System.DateTime> ngayNhapDenNgay, Nullable<System.DateTime> ngayBaoDuongTuNgay, Nullable<System.DateTime> ngayBaoDuongDenNgay, Nullable<int> iDCongTy, Nullable<int> iDKieuBaoDuong, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, string trangThai)
        {
            var ngayNhapTuNgayParameter = ngayNhapTuNgay.HasValue ?
                new ObjectParameter("NgayNhapTuNgay", ngayNhapTuNgay) :
                new ObjectParameter("NgayNhapTuNgay", typeof(System.DateTime));
    
            var ngayNhapDenNgayParameter = ngayNhapDenNgay.HasValue ?
                new ObjectParameter("NgayNhapDenNgay", ngayNhapDenNgay) :
                new ObjectParameter("NgayNhapDenNgay", typeof(System.DateTime));
    
            var ngayBaoDuongTuNgayParameter = ngayBaoDuongTuNgay.HasValue ?
                new ObjectParameter("NgayBaoDuongTuNgay", ngayBaoDuongTuNgay) :
                new ObjectParameter("NgayBaoDuongTuNgay", typeof(System.DateTime));
    
            var ngayBaoDuongDenNgayParameter = ngayBaoDuongDenNgay.HasValue ?
                new ObjectParameter("NgayBaoDuongDenNgay", ngayBaoDuongDenNgay) :
                new ObjectParameter("NgayBaoDuongDenNgay", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDKieuBaoDuongParameter = iDKieuBaoDuong.HasValue ?
                new ObjectParameter("IDKieuBaoDuong", iDKieuBaoDuong) :
                new ObjectParameter("IDKieuBaoDuong", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoDanhSachBaoDuong_Result>("sp_BaoCaoDanhSachBaoDuong", ngayNhapTuNgayParameter, ngayNhapDenNgayParameter, ngayBaoDuongTuNgayParameter, ngayBaoDuongDenNgayParameter, iDCongTyParameter, iDKieuBaoDuongParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, trangThaiParameter);
        }
    
        public virtual int sp_BaoCaoDuKienBaoDuong(Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo, Nullable<int> soNgayPhamViCanhBao, Nullable<int> soNgayGanNhatTinhTanSuat, Nullable<System.DateTime> baoDuongTuNgay, Nullable<System.DateTime> baoDuongDenNgay)
        {
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var soNgayPhamViCanhBaoParameter = soNgayPhamViCanhBao.HasValue ?
                new ObjectParameter("SoNgayPhamViCanhBao", soNgayPhamViCanhBao) :
                new ObjectParameter("SoNgayPhamViCanhBao", typeof(int));
    
            var soNgayGanNhatTinhTanSuatParameter = soNgayGanNhatTinhTanSuat.HasValue ?
                new ObjectParameter("SoNgayGanNhatTinhTanSuat", soNgayGanNhatTinhTanSuat) :
                new ObjectParameter("SoNgayGanNhatTinhTanSuat", typeof(int));
    
            var baoDuongTuNgayParameter = baoDuongTuNgay.HasValue ?
                new ObjectParameter("BaoDuongTuNgay", baoDuongTuNgay) :
                new ObjectParameter("BaoDuongTuNgay", typeof(System.DateTime));
    
            var baoDuongDenNgayParameter = baoDuongDenNgay.HasValue ?
                new ObjectParameter("BaoDuongDenNgay", baoDuongDenNgay) :
                new ObjectParameter("BaoDuongDenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoCaoDuKienBaoDuong", iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter, soNgayPhamViCanhBaoParameter, soNgayGanNhatTinhTanSuatParameter, baoDuongTuNgayParameter, baoDuongDenNgayParameter);
        }
    
        public virtual int sp_DinhMucNhienLieu(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DinhMucNhienLieu", startDateParameter, endDateParameter, iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter);
        }
    
        public virtual int sp_NhatKyHoatDong(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NhatKyHoatDong", startDateParameter, endDateParameter, iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter);
        }
    
        public virtual int sp_NhatKyHoatDongThucTe(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> iDCongTy, Nullable<int> iDNhomTrangThietBi, Nullable<int> iDLoaiTrangThietBi, string bienSo)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var iDCongTyParameter = iDCongTy.HasValue ?
                new ObjectParameter("IDCongTy", iDCongTy) :
                new ObjectParameter("IDCongTy", typeof(int));
    
            var iDNhomTrangThietBiParameter = iDNhomTrangThietBi.HasValue ?
                new ObjectParameter("IDNhomTrangThietBi", iDNhomTrangThietBi) :
                new ObjectParameter("IDNhomTrangThietBi", typeof(int));
    
            var iDLoaiTrangThietBiParameter = iDLoaiTrangThietBi.HasValue ?
                new ObjectParameter("IDLoaiTrangThietBi", iDLoaiTrangThietBi) :
                new ObjectParameter("IDLoaiTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NhatKyHoatDongThucTe", startDateParameter, endDateParameter, iDCongTyParameter, iDNhomTrangThietBiParameter, iDLoaiTrangThietBiParameter, bienSoParameter);
        }
    
        public virtual int sp_ReportSkySoftData(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ReportSkySoftData", startDateParameter, endDateParameter);
        }
    
        public virtual int sp_SkySoft_GetData(Nullable<int> iDTrangThietBi, string bienSo, Nullable<System.DateTime> ngayHoatDong, Nullable<double> soPhut, Nullable<double> soKm)
        {
            var iDTrangThietBiParameter = iDTrangThietBi.HasValue ?
                new ObjectParameter("IDTrangThietBi", iDTrangThietBi) :
                new ObjectParameter("IDTrangThietBi", typeof(int));
    
            var bienSoParameter = bienSo != null ?
                new ObjectParameter("BienSo", bienSo) :
                new ObjectParameter("BienSo", typeof(string));
    
            var ngayHoatDongParameter = ngayHoatDong.HasValue ?
                new ObjectParameter("NgayHoatDong", ngayHoatDong) :
                new ObjectParameter("NgayHoatDong", typeof(System.DateTime));
    
            var soPhutParameter = soPhut.HasValue ?
                new ObjectParameter("SoPhut", soPhut) :
                new ObjectParameter("SoPhut", typeof(double));
    
            var soKmParameter = soKm.HasValue ?
                new ObjectParameter("SoKm", soKm) :
                new ObjectParameter("SoKm", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SkySoft_GetData", iDTrangThietBiParameter, bienSoParameter, ngayHoatDongParameter, soPhutParameter, soKmParameter);
        }
    
        public virtual int sp_TinhHanBaoDuongTheoGioTungXe(Nullable<int> iD, Nullable<double> tanSuatHoatDong, Nullable<System.DateTime> ngayNhapGanNhat, Nullable<double> soGioNhapGanNhat, ObjectParameter ngayBaoDuongTiepTheo, ObjectParameter soNgayConLaiChoLanBaoDuongTiepTheo, ObjectParameter soGioMocBaoDuongTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tanSuatHoatDongParameter = tanSuatHoatDong.HasValue ?
                new ObjectParameter("tanSuatHoatDong", tanSuatHoatDong) :
                new ObjectParameter("tanSuatHoatDong", typeof(double));
    
            var ngayNhapGanNhatParameter = ngayNhapGanNhat.HasValue ?
                new ObjectParameter("ngayNhapGanNhat", ngayNhapGanNhat) :
                new ObjectParameter("ngayNhapGanNhat", typeof(System.DateTime));
    
            var soGioNhapGanNhatParameter = soGioNhapGanNhat.HasValue ?
                new ObjectParameter("soGioNhapGanNhat", soGioNhapGanNhat) :
                new ObjectParameter("soGioNhapGanNhat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhHanBaoDuongTheoGioTungXe", iDParameter, tanSuatHoatDongParameter, ngayNhapGanNhatParameter, soGioNhapGanNhatParameter, ngayBaoDuongTiepTheo, soNgayConLaiChoLanBaoDuongTiepTheo, soGioMocBaoDuongTiepTheo);
        }
    
        public virtual int sp_TinhHanBaoDuongTheoKmTungXe(Nullable<int> iD, Nullable<double> tanSuatHoatDong, Nullable<System.DateTime> ngayNhapGanNhat, Nullable<double> soKmNhapGanNhat, ObjectParameter ngayBaoDuongTiepTheo, ObjectParameter soNgayConLaiChoLanBaoDuongTiepTheo, ObjectParameter soKmMocBaoDuongTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tanSuatHoatDongParameter = tanSuatHoatDong.HasValue ?
                new ObjectParameter("tanSuatHoatDong", tanSuatHoatDong) :
                new ObjectParameter("tanSuatHoatDong", typeof(double));
    
            var ngayNhapGanNhatParameter = ngayNhapGanNhat.HasValue ?
                new ObjectParameter("ngayNhapGanNhat", ngayNhapGanNhat) :
                new ObjectParameter("ngayNhapGanNhat", typeof(System.DateTime));
    
            var soKmNhapGanNhatParameter = soKmNhapGanNhat.HasValue ?
                new ObjectParameter("soKmNhapGanNhat", soKmNhapGanNhat) :
                new ObjectParameter("soKmNhapGanNhat", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhHanBaoDuongTheoKmTungXe", iDParameter, tanSuatHoatDongParameter, ngayNhapGanNhatParameter, soKmNhapGanNhatParameter, ngayBaoDuongTiepTheo, soNgayConLaiChoLanBaoDuongTiepTheo, soKmMocBaoDuongTiepTheo);
        }
    
        public virtual int sp_TinhHanBaoDuongTheoThangTungXe(Nullable<int> iD, ObjectParameter ngayBaoDuongGanNhat, ObjectParameter ngayBaoDuongTiepTheo, ObjectParameter soNgayConLaiChoLanBaoDuongTiepTheo, ObjectParameter mocBaoDuongTiepTheo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhHanBaoDuongTheoThangTungXe", iDParameter, ngayBaoDuongGanNhat, ngayBaoDuongTiepTheo, soNgayConLaiChoLanBaoDuongTiepTheo, mocBaoDuongTiepTheo);
        }
    
        public virtual int sp_TinhTanSuatHoatDongThucTe(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhTanSuatHoatDongThucTe", tuNgayParameter, denNgayParameter);
        }
    
        public virtual int sp_TinhTanSuatHoatDongThucTeTungNgay(Nullable<int> iDTrangThietBi, Nullable<System.DateTime> ngayHoatDong)
        {
            var iDTrangThietBiParameter = iDTrangThietBi.HasValue ?
                new ObjectParameter("IDTrangThietBi", iDTrangThietBi) :
                new ObjectParameter("IDTrangThietBi", typeof(int));
    
            var ngayHoatDongParameter = ngayHoatDong.HasValue ?
                new ObjectParameter("NgayHoatDong", ngayHoatDong) :
                new ObjectParameter("NgayHoatDong", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TinhTanSuatHoatDongThucTeTungNgay", iDTrangThietBiParameter, ngayHoatDongParameter);
        }
    
        public virtual int sp_TransferDataFromGPS(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TransferDataFromGPS", startDateParameter, endDateParameter);
        }
    
        public virtual int sp_UpdateNapNhienLieu(Nullable<int> iDTrangThietBi, string ngayNap, Nullable<double> soLuong)
        {
            var iDTrangThietBiParameter = iDTrangThietBi.HasValue ?
                new ObjectParameter("IDTrangThietBi", iDTrangThietBi) :
                new ObjectParameter("IDTrangThietBi", typeof(int));
    
            var ngayNapParameter = ngayNap != null ?
                new ObjectParameter("NgayNap", ngayNap) :
                new ObjectParameter("NgayNap", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNapNhienLieu", iDTrangThietBiParameter, ngayNapParameter, soLuongParameter);
        }
    
        public virtual int sp_UpdateNhatKyHoatDong(Nullable<int> iDTrangThietBi, string ngayHoatDong, Nullable<double> soGio_SoKm)
        {
            var iDTrangThietBiParameter = iDTrangThietBi.HasValue ?
                new ObjectParameter("IDTrangThietBi", iDTrangThietBi) :
                new ObjectParameter("IDTrangThietBi", typeof(int));
    
            var ngayHoatDongParameter = ngayHoatDong != null ?
                new ObjectParameter("NgayHoatDong", ngayHoatDong) :
                new ObjectParameter("NgayHoatDong", typeof(string));
    
            var soGio_SoKmParameter = soGio_SoKm.HasValue ?
                new ObjectParameter("SoGio_SoKm", soGio_SoKm) :
                new ObjectParameter("SoGio_SoKm", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNhatKyHoatDong", iDTrangThietBiParameter, ngayHoatDongParameter, soGio_SoKmParameter);
        }
    }
}
