//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietBaoDuongCongViec
    {
        public long ID { get; set; }
        public long IDChiTietBaoDuong { get; set; }
        public Nullable<int> IDCongViec { get; set; }
        public int IDCapBaoDuong { get; set; }
    
        public virtual tblChiTietBaoDuong tblChiTietBaoDuong { get; set; }
        public virtual tblCongViec tblCongViec { get; set; }
    }
}
