//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCapBaoDuongCongViec
    {
        public int ID { get; set; }
        public int IDHangMucLoaiTrangThietBi { get; set; }
        public int IDCapBaoDuong { get; set; }
        public int IDCongViec { get; set; }
    
        public virtual tblCapBaoDuong tblCapBaoDuong { get; set; }
        public virtual tblCongViec tblCongViec { get; set; }
        public virtual tblHangMucLoaiTrangThietBi tblHangMucLoaiTrangThietBi { get; set; }
    }
}
