//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCongViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCongViec()
        {
            this.tblChiTietBaoDuongCongViecs = new HashSet<tblChiTietBaoDuongCongViec>();
            this.tblCapBaoDuongCongViecs = new HashSet<tblCapBaoDuongCongViec>();
        }
    
        public int ID { get; set; }
        public string MaCongViec { get; set; }
        public string TenCongViec { get; set; }
        public string TenEng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietBaoDuongCongViec> tblChiTietBaoDuongCongViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCapBaoDuongCongViec> tblCapBaoDuongCongViecs { get; set; }
    }
}
