//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietBaoDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblChiTietBaoDuong()
        {
            this.tblChiTietBaoDuongCongViecs = new HashSet<tblChiTietBaoDuongCongViec>();
        }
    
        public long ID { get; set; }
        public int IDTheBaoDuong { get; set; }
        public int IDHangMucBaoDuong { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsRequiresRepair { get; set; }
    
        public virtual tblHangMucBaoDuong tblHangMucBaoDuong { get; set; }
        public virtual tblTheBaoDuong tblTheBaoDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietBaoDuongCongViec> tblChiTietBaoDuongCongViecs { get; set; }
    }
}
