//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHangMucLoaiTrangThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHangMucLoaiTrangThietBi()
        {
            this.tblCapBaoDuongCongViecs = new HashSet<tblCapBaoDuongCongViec>();
        }
    
        public int ID { get; set; }
        public int IDHangMuc { get; set; }
        public int IDLoaiTrangThietBi { get; set; }
    
        public virtual tblHangMucBaoDuong tblHangMucBaoDuong { get; set; }
        public virtual tblLoaiTrangThietBi tblLoaiTrangThietBi { get; set; }
        public virtual tblLoaiTrangThietBi tblLoaiTrangThietBi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCapBaoDuongCongViec> tblCapBaoDuongCongViecs { get; set; }
    }
}
