//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiTrangThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoaiTrangThietBi()
        {
            this.tblTrangThietBis = new HashSet<tblTrangThietBi>();
            this.tblHangMucLoaiTrangThietBis = new HashSet<tblHangMucLoaiTrangThietBi>();
            this.tblHangMucLoaiTrangThietBis1 = new HashSet<tblHangMucLoaiTrangThietBi>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public int SoThuTuHienThi { get; set; }
        public string GhiChu { get; set; }
        public string DonViGhiNhanHoatDong { get; set; }
        public Nullable<int> IDLoaiBaoDuong { get; set; }
        public Nullable<int> IDNhomTrangThietBi { get; set; }
        public string TenEng { get; set; }
    
        public virtual tblLoaiBaoDuong tblLoaiBaoDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrangThietBi> tblTrangThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHangMucLoaiTrangThietBi> tblHangMucLoaiTrangThietBis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHangMucLoaiTrangThietBi> tblHangMucLoaiTrangThietBis1 { get; set; }
        public virtual tblNhomTrangThietBi tblNhomTrangThietBi { get; set; }
    }
}
