//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiBaoDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLoaiBaoDuong()
        {
            this.tblCapBaoDuongs = new HashSet<tblCapBaoDuong>();
            this.tblLoaiTrangThietBis = new HashSet<tblLoaiTrangThietBi>();
        }
    
        public int IDLoaiBaoDuong { get; set; }
        public int IDKieuBaoDuong { get; set; }
        public string Ten { get; set; }
        public double SoLuongBaoDuongDinhKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCapBaoDuong> tblCapBaoDuongs { get; set; }
        public virtual tblKieuBaoDuong tblKieuBaoDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoaiTrangThietBi> tblLoaiTrangThietBis { get; set; }
    }
}
