//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhatKyHoatDong
    {
        public long ID { get; set; }
        public int IDTrangThietBi { get; set; }
        public System.DateTime NgayHoatDong { get; set; }
        public Nullable<double> SoGio { get; set; }
        public Nullable<double> SoKm { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblTrangThietBi tblTrangThietBi { get; set; }
    }
}
