//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhomHangMucBaoDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhomHangMucBaoDuong()
        {
            this.tblHangMucBaoDuongs = new HashSet<tblHangMucBaoDuong>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public short SoThuTuHienThi { get; set; }
        public Nullable<int> IDParent { get; set; }
        public string TenEng { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHangMucBaoDuong> tblHangMucBaoDuongs { get; set; }
    }
}
