//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhomTrangThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhomTrangThietBi()
        {
            this.tblLoaiTrangThietBis = new HashSet<tblLoaiTrangThietBi>();
        }
    
        public int ID { get; set; }
        public string TenNhom { get; set; }
        public string GhiChu { get; set; }
        public string TenNhomEng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLoaiTrangThietBi> tblLoaiTrangThietBis { get; set; }
    }
}
