//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhieuSuaChua
    {
        public int ID { get; set; }
        public string MaPhieu { get; set; }
        public int IDTrangThietBi { get; set; }
        public string NguoiSuaChua { get; set; }
        public System.DateTime NgaySuaChua { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<double> SoGioHoacKm { get; set; }
        public Nullable<System.DateTime> NgayVaoXuong { get; set; }
        public Nullable<System.DateTime> NgayXuatXuong { get; set; }
        public string PathOfFileUpload { get; set; }
    
        public virtual tblTrangThietBi tblTrangThietBi { get; set; }
    }
}
