//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRightsInRole
    {
        public int ID { get; set; }
        public int IdRight { get; set; }
        public int IdRole { get; set; }
    
        public virtual tblRight tblRight { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
