//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSkySoft
    {
        public long ID { get; set; }
        public int IdTrangThietBi { get; set; }
        public string BienSo { get; set; }
        public System.DateTime NgayHoatDong { get; set; }
        public double SoPhut { get; set; }
        public double SoKm { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> IsTransfered { get; set; }
    }
}
