//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTheBaoDuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTheBaoDuong()
        {
            this.tblChiTietBaoDuongs = new HashSet<tblChiTietBaoDuong>();
        }
    
        public int ID { get; set; }
        public int IDTrangThietBi { get; set; }
        public int IDHuHong { get; set; }
        public string NguoiBaoDuong { get; set; }
        public System.DateTime NgayBaoDuong { get; set; }
        public string TrangThaiKhaiThac { get; set; }
        public int IDCapBaoDuong { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiSua { get; set; }
        public string MaThe { get; set; }
        public Nullable<double> SoGioHoacKm { get; set; }
        public Nullable<System.DateTime> NgayVaoXuong { get; set; }
        public Nullable<System.DateTime> NgayXuatXuong { get; set; }
        public string PathOfFileUpload { get; set; }
    
        public virtual tblCapBaoDuong tblCapBaoDuong { get; set; }
        public virtual tblLoaiHuHong tblLoaiHuHong { get; set; }
        public virtual tblTrangThietBi tblTrangThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietBaoDuong> tblChiTietBaoDuongs { get; set; }
    }
}
