//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrangThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTrangThietBi()
        {
            this.tblDinhMucNhienLieux = new HashSet<tblDinhMucNhienLieu>();
            this.tblDinhMucTheoNgays = new HashSet<tblDinhMucTheoNgay>();
            this.tblNapNhienLieux = new HashSet<tblNapNhienLieu>();
            this.tblNhatKyHoatDongs = new HashSet<tblNhatKyHoatDong>();
            this.tblTanSuatHoatDongs = new HashSet<tblTanSuatHoatDong>();
            this.tblTheBaoDuongs = new HashSet<tblTheBaoDuong>();
            this.tblPhieuSuaChuas = new HashSet<tblPhieuSuaChua>();
        }
    
        public int ID { get; set; }
        public string MaTaiSan { get; set; }
        public string Ten { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public string NuocSanXuat { get; set; }
        public Nullable<System.DateTime> NgayDangKiemLanDau { get; set; }
        public Nullable<int> SoThangDangKiemDinhKy { get; set; }
        public string BienSo { get; set; }
        public string SoKhung { get; set; }
        public string LoaiMay { get; set; }
        public string SoMay { get; set; }
        public string GhiChu { get; set; }
        public int IDCongTy { get; set; }
        public int IDLoaiTrangThietBi { get; set; }
        public Nullable<int> IDQuyTrinhBaoDuong { get; set; }
        public Nullable<System.DateTime> NgayBaoDuongGanNhat { get; set; }
        public Nullable<double> SoKmBaoDuongGanNhat { get; set; }
        public Nullable<double> SoGioBaoDuongGanNhat { get; set; }
        public Nullable<bool> CanhBaoDangKiem { get; set; }
        public string BaoDuongTheo { get; set; }
    
        public virtual tblCongTy tblCongTy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDinhMucNhienLieu> tblDinhMucNhienLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDinhMucTheoNgay> tblDinhMucTheoNgays { get; set; }
        public virtual tblLoaiTrangThietBi tblLoaiTrangThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNapNhienLieu> tblNapNhienLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhatKyHoatDong> tblNhatKyHoatDongs { get; set; }
        public virtual tblQuyTrinhBaoDuong tblQuyTrinhBaoDuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTanSuatHoatDong> tblTanSuatHoatDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTheBaoDuong> tblTheBaoDuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuSuaChua> tblPhieuSuaChuas { get; set; }
    }
}
