//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVatTu()
        {
            this.tblCapBaoDuongVatTus = new HashSet<tblCapBaoDuongVatTu>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public decimal SoLuongTonKho { get; set; }
        public int IDLoaiVatTu { get; set; }
        public int IDNhaCungCap { get; set; }
        public int IDPhongBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCapBaoDuongVatTu> tblCapBaoDuongVatTus { get; set; }
        public virtual tblLoaiVatTu tblLoaiVatTu { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblPhongBan tblPhongBan { get; set; }
    }
}
